export enum PopupPath {
  INDEX = '/',
  LOGIN = '/login',
  TRANSACTION_APPROVAL = '/approval/tx',
  ORIGIN_APPROVAL = '/approval/origin',
  SETTINGS = '/settings',
  SETTINGS_ADVANCED = '/settings/advanced',
  SETTINGS_SECURITY = '/settings/security',
  SETTINGS_RPC = '/settings/rpc',
  SETTINGS_CONNECTED_SITES = '/settings/connected-sites',
  SETTINGS_AUTO_LOCK = '/settings/auto-lock',
  SETTINGS_CLEAR_CACHE = '/settings/clear-cache',
  SETTINGS_RECOVERY_PASSPHRASE = '/settings/recovery-passphrase',
  SETTINGS_FULL_VIEWING_KEY = '/settings/full-viewing-key',
  SETTINGS_SPEND_KEY = '/settings/spend-key',
}
