export enum PopupPath {
  INDEX = '/',
  LOGIN = '/login',
  SETTINGS = '/settings',
  SETTINGS_ADVANCED = '/settings/advanced',
  SETTINGS_SECURITY = '/settings/security',
  SETTINGS_NETWORKS = '/settings/network',
  SETTINGS_NETWORK_NAME = '/settings/network/:name',
  SETTINGS_PERMISSION = '/settings/permission',
  SETTINGS_CONNECTED_SITES = '/settings/connected-sites',
  SETTINGS_AUTO_LOCK = '/settings/auto-lock',
  SETTINGS_CLEAR_CACHE = '/settings/clear-cache',
  SETTINGS_RECOVERY_PASSPHRASE = '/settings/recovery-passphrase',
  SETTINGS_FULL_VIEWING_KEY = '/settings/full-viewing-key',
  SETTINGS_SPEND_KEY = '/settings/spend-key',
  ACCOUNTS = '/accounts',
}
