app = "veil-ci"
primary_region = "iad"

[build]
  dockerfile = "ci/containerfiles/Containerfile-veil-fly"
  [build.args]
  BUILDKIT_STEP_LOG_MAX_SIZE = "50000000"

  [build.settings]
    size = "shared-cpu-8x"

[env]
  NODE_ENV = "production"
  PENUMBRA_GRPC_ENDPOINT = "https://penumbra.crouton.digital/"
  PENUMBRA_CHAIN_ID = "penumbra-1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 200
    soft_limit = 100

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  timeout = "10s"
  path = "/explore"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
