export enum PagePath {
  INDEX = '/',
  SWAP = '/swap',
  SEND = '/send',
  STAKING = '/staking',
  RECEIVE = '/send/receive',
  TRANSACTIONS = '/dashboard/transactions',
  DASHBOARD = '/dashboard',
  DEPOSIT_SKIP = '/deposit/skip',
  DEPOSIT_MANUAL = '/deposit/manual',
  WITHDRAW = '/withdraw',
  NFTS = '/dashboard/nfts',
  TRANSACTION_DETAILS = '/tx/:hash',
  V2_PORTFOLIO = '/v2/portfolio',
  V2_TRANSACTIONS_FULL = '/v2/portfolio/transactions',
}
