---
name: Deploy dex-explorer
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-container:
    name: Build container
    uses: ./.github/workflows/container.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  deploy-preview:
    name: Deploy dex-explorer to preview
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    needs:
      - build-container
    runs-on: ubuntu-latest
    steps:
      - id: gcloudauth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/1006847873719/locations/global/workloadIdentityPools/gh-runner-pool/providers/my-provider'
          service_account: 'github-actions@penumbra-sl-testnet.iam.gserviceaccount.com'

      - name: get gke credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: testnet
          project_id: penumbra-sl-testnet
          location: us-central1

      # We assume that dex-explorer has been deployed to the cluster already.
      # This task merely "bounces" the service, so that a fresh container is pulled.
      - name: bounce dex-explorer
        run: kubectl rollout restart deployment dex-explorer-preview

  deploy-testnet:
    name: Deploy dex-explorer to testnet
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    needs:
      - build-container
    runs-on: ubuntu-latest
    steps:
      - id: gcloudauth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/1006847873719/locations/global/workloadIdentityPools/gh-runner-pool/providers/my-provider'
          service_account: 'github-actions@penumbra-sl-testnet.iam.gserviceaccount.com'

      - name: get gke credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: testnet
          project_id: penumbra-sl-testnet
          location: us-central1

      # We assume that dex-explorer has been deployed to the cluster already.
      # This task merely "bounces" the service, so that a fresh container is pulled.
      - name: bounce dex-explorer
        run: kubectl rollout restart deployment dex-explorer-testnet
