# A justfile for veil development.
# Documents common tasks for local dev.

# run the app locally with live reload, via pnpm
dev:
  pnpm install
  pnpm dev

# build container image
container:
  podman buildx build -t ghcr.io/penumbra-zone/veil -f ../../ci/containerfiles/Containerfile-veil ../..

# build, then run the container image. uses local env vars.
run-container: container
  podman run \
    -e PENUMBRA_INDEXER_ENDPOINT -e PENUMBRA_INDEXER_CA_CERT -e PENUMBRA_GRPC_ENDPOINT \
    -e PENUMBRA_CHAIN_ID -e PENUMBRA_CUILOA_URL \
    -p 3000:3000 -it ghcr.io/penumbra-zone/veil

# Deploy the current branch to fly.io
deploy:
  cd ../../ && just deploy
