import type { ActionPlan } from '@penumbra-zone/protobuf/penumbra/core/transaction/v1/transaction_pb';

export const actionCountsInit: Record<NonNullable<ActionPlan['action']['case']>, number> = {
  actionDutchAuctionEnd: 0,
  actionDutchAuctionSchedule: 0,
  actionDutchAuctionWithdraw: 0,
  actionLiquidityTournamentVote: 0,
  communityPoolDeposit: 0,
  communityPoolOutput: 0,
  communityPoolSpend: 0,
  delegate: 0,
  delegatorVote: 0,
  ibcRelayAction: 0,
  ics20Withdrawal: 0,
  output: 0,
  positionClose: 0,
  positionOpen: 0,
  positionRewardClaim: 0,
  positionWithdraw: 0,
  proposalDepositClaim: 0,
  proposalSubmit: 0,
  proposalWithdraw: 0,
  spend: 0,
  swap: 0,
  swapClaim: 0,
  undelegate: 0,
  undelegateClaim: 0,
  validatorDefinition: 0,
  validatorVote: 0,
} as const;
