# Deploys the static website for the UI storybook to "preview" environment,
# on every merge into main branch.
name: Deploy UI to preview
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup nix
        uses: ./.github/actions/setup-nix

      - name: setup turbo
        uses: ./.github/actions/setup-turbo

      - name: build all packages, including ui
        run: nix develop --command just build

      - name: Build static site
        run: nix develop --command pnpm build-storybook
        working-directory: packages/ui

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PENUMBRA_UI }}
          channelId: live
          target: preview
          entryPoint: packages/ui
          projectId: penumbra-ui
