# Deploys the static website for the UI storybook to final prod website,
# on every tag push into main branch.
name: Deploy UI to stable channel
on:
  # Support ad-hoc runs
  workflow_dispatch:
  # Run automatically on tag push
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'
jobs:
  turbo-compile:
    name: Compile
    uses: ./.github/workflows/compile-wasm.yml

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: turbo-compile
    steps:
      - uses: actions/checkout@v4
      - id: built
        uses: buildjet/cache@v4
        with:
          path: .turbo
          key: ${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.ref }}-${{ github.sha }}-built
          restore-keys: ${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.ref }}-${{ github.sha }}-compiled

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build all packages that UI depends on
        run: pnpm exec turbo build --filter=./packages/ui

      - name: Build static site
        run: pnpm build-storybook
        working-directory: packages/ui

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PENUMBRA_UI }}
          channelId: live
          target: stable
          entryPoint: packages/ui
          projectId: penumbra-ui
