# Deploys the static website for the UI storybook to "preview" environment,
# on every merge into main branch.
name: Deploy UI to preview
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  turbo-compile:
    name: Compile
    uses: ./.github/workflows/compile-wasm.yml

  build_and_deploy:
    needs: turbo-compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: built
        uses: buildjet/cache@v4
        with:
          path: .turbo
          key: ${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.ref }}-${{ github.sha }}-built
          restore-keys: ${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.ref }}-${{ github.sha }}-compiled

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build all packages that UI depends on
        run: pnpm exec turbo build --cache-dir=.turbo --filter=./packages/ui

      - name: Build static site
        run: pnpm build-storybook
        working-directory: packages/ui

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PENUMBRA_UI }}
          channelId: live
          target: preview
          entryPoint: packages/ui
          projectId: penumbra-ui
