# Deploys the static website for the UI storybook to final prod website,
# on every tag push into main branch.
name: Deploy UI to stable channel
on:
  # Support ad-hoc runs
  workflow_dispatch:
  # Run automatically on tag push
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup nix
        uses: ./.github/actions/setup-nix

      - name: setup turbo
        uses: ./.github/actions/setup-turbo

      - name: build all packages, including ui
        run: nix develop --command just build

      - name: Build static site
        run: nix develop --command pnpm build-storybook
        working-directory: packages/ui

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PENUMBRA_UI }}
          channelId: live
          target: stable
          entryPoint: packages/ui
          projectId: penumbra-ui
