name: Cleanup PR Fly.io Deployments

on:
  pull_request:
    types: [closed]
  schedule:
    # Run every hour to check for deployments older than 12 hours
    - cron: '0 * * * *'

jobs:
  cleanup-on-close:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Set up Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Delete Fly app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          APP_NAME="veil-pr-${{ github.event.pull_request.number }}"

          # Check if app exists before attempting deletion
          if flyctl apps list | grep -q "$APP_NAME"; then
            echo "Deleting app: $APP_NAME"
            flyctl apps destroy "$APP_NAME" --yes
          else
            echo "App $APP_NAME not found, skipping deletion"
          fi

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `### Deployment Cleaned Up

            The Fly.io deployment for this PR has been removed.

            Reason: PR closed
            Cleanup time: ${new Date().toISOString()}`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });

  cleanup-scheduled:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: List and cleanup old deployments
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: ./ci/fly-cleanup-pr-deployments
