# Publishes extension to chrome web store when a release is made in github.

# `maniftest.json` should already be updated to the desired version before release.
# make sure download-proving-keys contains the correct version tag.

# https://chrome.google.com/webstore/detail/penumbra-wallet/lkpmkhpnhknhmibgnmmhdhgdilepfghe
name: Test Publish flow

# Temp for testing
on:
  workflow_call:
  workflow_dispatch:
  pull_request:

jobs:
  turbo-compile:
    name: Compile
    uses: ./.github/workflows/compile-wasm.yml

  publish:
    name: Publish extension
    runs-on: buildjet-16vcpu-ubuntu-2204
    needs: turbo-compile

    steps:
      - uses: actions/checkout@v4
      - id: ext:publish
        uses: buildjet/cache@v3
        with:
          path: .turbo
          key: ${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.ref }}-${{ github.sha }}-ext:publish
          restore-keys: ${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.ref }}-${{ github.sha }}-compiled
      - uses: pnpm/action-setup@v2
      - uses: buildjet/setup-node@v4
        with:
          node-version: '21'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm turbo telemetry disable
      - run: pnpm turbo build --cache-dir=.turbo

      - name: Package up extension
        run: zip -r dist.zip apps/extension/dist
