name: Test Publish flow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Temp for testing
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  turbo-compile:
    name: Compile
    uses: ./.github/workflows/compile-wasm.yml

  publish:
    name: Build
    runs-on: buildjet-2vcpu-ubuntu-2204
    needs: turbo-compile
    steps:
      - uses: actions/checkout@v4
      - id: built
        uses: buildjet/cache@v3
        with:
          path: .turbo
          key: ${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.ref }}-${{ github.sha }}-built
          restore-keys: ${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.ref }}-${{ github.sha }}-compiled
      - uses: pnpm/action-setup@v2
      - uses: buildjet/setup-node@v4
        with:
          node-version: '21'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm turbo telemetry disable
      - run: pnpm turbo build --cache-dir=.turbo

      - name: Package up extension
        run: zip -r dist.zip apps/extension/dist
