name: WASM
on: workflow_call

# workflow_call for optional forcing

jobs:
  test-rust:
    name: 'test:rust'
    runs-on: buildjet-16vcpu-ubuntu-2204 # buildjet for rust, github standard for everything else
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3 # turbo cache, shared between buildjet and github
        id: turbo-cache
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: pnpm/action-setup@v2
      - uses: buildjet/setup-node@v4 # node cache, distinct between buildjet and github
        with:
          node-version: '21'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile # commit your lockfile
      - run: pnpm turbo telemetry disable

      - uses: dtolnay/rust-toolchain@stable # rust only on buildjet
        with:
          targets: wasm32-unknown-unknown
      - uses: astriaorg/buildjet-rust-cache@v2.5.1 # buildjet rust cache
      - uses: jetli/wasm-pack-action@v0.4.0 # preinstall wasm-pack
        with:
          version: 'latest'
      - uses: browser-actions/setup-firefox@v1 # wasm tests in ffx

      - run: pnpm turbo test:rust --cache-dir=.turbo # test wasm

      - run: cargo tree --invert mio --edges features # debug tree
        if: failure()
        working-directory: packages/wasm/crate
